services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mysql-port.address=:3306"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=webmaster@midoctor24h.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Configuraciones adicionales para webhooks
      - "--serversTransport.insecureSkipVerify=true"
      - "--global.sendAnonymousUsage=false"
      # Timeouts para webhooks
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=60s"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=60s"
      - "--entrypoints.websecure.transport.respondingTimeouts.idleTimeout=180s"
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
      - "./traefik.yml:/traefik.yml"
    networks:
      - proxy

networks:
  proxy:
    external: true